resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    node0 ansible_host=${yandex_compute_instance.master01.network_interface.0.nat_ip_address} ip=${yandex_compute_instance.master01.network_interface.0.ip_address}
    node1 ansible_host=${yandex_compute_instance.worker01.network_interface.0.nat_ip_address} ip=${yandex_compute_instance.worker01.network_interface.0.ip_address}
    node2 ansible_host=${yandex_compute_instance.worker02.network_interface.0.nat_ip_address} ip=${yandex_compute_instance.worker02.network_interface.0.ip_address}

    [kube_control_plane]
    node0

    [etcd]
    node0

    [kube_node]
    node1
    node2

    [k8s_cluster:children]
    kube_node
    kube_control_plane

    [k8s_cluster:vars]
    ansible_user=ubuntu

    [kube_control_plane:vars]
    apiserver_cert_extra_sans=${yandex_compute_instance.master01.network_interface.0.nat_ip_address}

    DOC
  filename = "../playbooks/inventory.yml"

  depends_on = [
    yandex_compute_instance.master01,
    yandex_compute_instance.worker01,
    yandex_compute_instance.worker02
  ]
}
