---
- name: Deploy nginx in Kuber
  gather_facts: True
  hosts: kube_control_plane
  tasks:
  - name: Create nginx manifest dir
    ansible.builtin.file:
      path: /opt/nginx
      state: directory
      mode: '0755'
#  - name: Copy nginx manifests
#    ansible.builtin.copy:
#      src: "../nginx/"
#      dest: /opt/nginx/
#      owner: root
#      group: root
#      mode: '0644'

  - name: Get nginx source git repo
    ansible.builtin.git:
      repo: https://github.com/Scandr/nginx_cicd_source.git
      dest: /opt/nginx

  - name: Create nginx namespace
    ansible.builtin.shell:
      cmd: "kubectl create ns nginx"

  - name: Create nginx service
    ansible.builtin.shell:
      cmd: "kubectl apply -f /opt/nginx/kuber_manifests/service.yml"

  - name: Create nginx service
    ansible.builtin.shell:
      cmd: "kubectl apply -f /opt/nginx/kuber_manifests/deployment.yml"
