---
- name: Install Jenkins in Kuber
  gather_facts: True
  hosts: kube_control_plane
  tasks:
  - name: Create jenkins manifest dir
    ansible.builtin.file:
      path: /opt/jenkins
      state: directory
      mode: '0755'

  - name: Copy jenkins manifests
    ansible.builtin.copy:
      src: jenkins_manifests/
      dest: /opt/jenkins/
      owner: root
      group: root
      mode: '0644'

  - name: Add Jenkins chart repo
    kubernetes.core.helm_repository:
      name: jenkins
      repo_url: "https://charts.jenkins.io"

  - name: Restart core dns (for some reason it is required to enable internet traffic)
    ansible.builtin.shell:
      cmd: "kubectl -n kube-system rollout restart deployment coredns"

  - name: Deploy latest Jenkins chart
    kubernetes.core.helm:
      name: jenkins
      chart_ref: jenkins/jenkins
      release_namespace: jenkins
      create_namespace: true
#      values_files:
#      - /opt/jenkins/values.yaml
      values:
#        kubernetesURL: "https://{{ ansible_eth0.ipv4.address }}"
        controller:
          image: "xillah/custom-jenkins"
          tagLabel: lts
          serviceType: NodePort
          serviceAnnotations:

          ingress:
            enabled: false
            ingressClassName: nginx
            hostName: "my.jenkins"
            path: "/jenkins"
          prometheus:
            enabled: true
          # Command to get list of current jenkins plugins installed
          # Jenkins.instance.pluginManager.plugins.each{ plugin ->   println ("${plugin.getShortName()}:${plugin.getVersion()}") } null
          #installPlugins:
          #  - kubernetes:4029.v5712230ccb_f8
          #  - workflow-aggregator:596.v8c21c963d92d
          #  - git:5.2.1
          #  - github:1.37.3.1
          #  - github-oauth:597.ve0c3480fcb_d0
          #  - github-branch-source:1767.va_7d01ea_c7256
          #  - pipeline-github-lib:42.v0739460cda_c4
          #  - blueocean-github-pipeline:1.27.9
          #  - generic-webhook-trigger:1.88.2
          #  - ghprb:1.42.2
          #  - pipeline-github:2.8-159.09e4403bc62f
          #  - github-pr-comment-build:96.v9ff13b69dd66
          #  - git-push:34.vd474e0fe7b_ec
          #  - git-tag-message:1.7.1
          #  - configuration-as-code:1670.v564dc8b_982d0
          #  - prometheus:2.4.1
          #  - multibranch-action-triggers:1.8.6
          #  - multibranch-scan-webhook-trigger:1.0.11
          #  - basic-branch-build-strategies:81.v05e333931c7d
          installPlugins:
            - antisamy-markup-formatter:162.v0e6ec0fcfcf6
            - apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
            - authentication-tokens:1.53.v1c90fd9191a_b_
            - basic-branch-build-strategies:81.v05e333931c7d
            - blueocean-commons:1.27.9
            - blueocean-core-js:1.27.9
            - blueocean-github-pipeline:1.27.9
            - blueocean-jwt:1.27.9
            - blueocean-pipeline-api-impl:1.27.9
            - blueocean-pipeline-scm-api:1.27.9
            - blueocean-rest-impl:1.27.9
            - blueocean-rest:1.27.9
            - blueocean-web:1.27.9
            - bootstrap5-api:5.3.2-3
            - bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
            - branch-api:2.1144.v1425d1c3d5a_7
            - caffeine-api:3.1.8-133.v17b_1ff2e0599
            - checks-api:2.0.2
            - cloudbees-folder:6.858.v898218f3609d
            - command-launcher:107.v773860566e2e
            - commons-lang3-api:3.13.0-62.v7d18e55f51e2
            - commons-text-api:1.11.0-95.v22a_d30ee5d36
            - configuration-as-code:1775.v810dc950b_514
            - credentials-binding:657.v2b_19db_7d6e6d
            - credentials:1311.vcf0a_900b_37c2
            - display-url-api:2.200.vb_9327d658781
            - durable-task:543.v262f6a_803410
            - echarts-api:5.4.3-2
            - favorite:2.208.v91d65b_7792a_c
            - font-awesome-api:6.5.1-2
            - generic-webhook-trigger:1.88.2
            - ghprb:1.42.2
            - git-client:4.6.0
            - git-push:34.vd474e0fe7b_ec
            - git-tag-message:1.7.1
            - git:5.2.1
            - github-api:1.318-461.v7a_c09c9fa_d63
            - github-branch-source:1772.va_69eda_d018d4
            - github-oauth:597.ve0c3480fcb_d0
            - github-pr-comment-build:96.v9ff13b69dd66
            - github:1.37.3.1
            - gson-api:2.10.1-15.v0d99f670e0a_7
            - htmlpublisher:1.32
            - instance-identity:185.v303dc7c645f9
            - ionicons-api:56.v1b_1c8c49374e
            - jackson2-api:2.16.1-373.ve709c6871598
            - jakarta-activation-api:2.0.1-3
            - jakarta-mail-api:2.0.1-3
            - javax-activation-api:1.2.0-6
            - javax-mail-api:1.6.2-9
            - jaxb:2.3.9-1
            - jdk-tool:73.vddf737284550
            - jenkins-design-language:1.27.9
            - jjwt-api:0.11.5-77.v646c772fddb_0
            - joda-time-api:2.12.6-21.vca_fd74418fb_7
            - jquery3-api:3.7.1-1
            - json-api:20231013-17.v1c97069404b_e
            - json-path-api:2.9.0-33.v2527142f2e1d
            - junit:1256.v002534a_5f33e
            - kubernetes-client-api:6.9.2-239.ve49a_3f285167
            - kubernetes-credentials:0.11
            - kubernetes:4179.v3b_88431df708
            - mailer:463.vedf8358e006b_
            - matrix-project:822.v01b_8c85d16d2
            - metrics:4.2.18-442.v02e107157925
            - mina-sshd-api-common:2.12.0-90.v9f7fb_9fa_3d3b_
            - mina-sshd-api-core:2.12.0-90.v9f7fb_9fa_3d3b_
            - multibranch-action-triggers:1.8.6
            - multibranch-scan-webhook-trigger:1.0.11
            - okhttp-api:4.11.0-157.v6852a_a_fa_ec11
            - pipeline-build-step:540.vb_e8849e1a_b_d8
            - pipeline-github-lib:42.v0739460cda_c4
            - pipeline-github:2.8-159.09e4403bc62f
            - pipeline-graph-analysis:202.va_d268e64deb_3
            - pipeline-groovy-lib:700.v0e341fa_57d53
            - pipeline-input-step:477.v339683a_8d55e
            - pipeline-milestone-step:111.v449306f708b_7
            - pipeline-model-api:2.2175.v76a_fff0a_2618
            - pipeline-model-definition:2.2175.v76a_fff0a_2618
            - pipeline-model-extensions:2.2175.v76a_fff0a_2618
            - pipeline-rest-api:2.34
            - pipeline-stage-step:305.ve96d0205c1c6
            - pipeline-stage-tags-metadata:2.2175.v76a_fff0a_2618
            - plain-credentials:143.v1b_df8b_d3b_e48
            - plugin-util-api:3.8.0
            - prism-api:1.29.0-10
            - prometheus:2.5.1
            - pubsub-light:1.18
            - scm-api:683.vb_16722fb_b_80b_
            - script-security:1313.v7a_6067dc7087
            - snakeyaml-api:2.2-111.vc6598e30cc65
            - ssh-credentials:308.ve4497b_ccd8f4
            - sshd:3.322.v159e91f6a_550
            - structs:337.v1b_04ea_4df7c8
            - token-macro:400.v35420b_922dcb_
            - trilead-api:2.133.vfb_8a_7b_9c5dd1
            - variant:60.v7290fc0eb_b_cd
            - workflow-aggregator:596.v8c21c963d92d
            - workflow-api:1283.v99c10937efcb_
            - workflow-basic-steps:1042.ve7b_140c4a_e0c
            - workflow-cps:3837.v305192405b_c0
            - workflow-durable-task-step:1313.vcb_970b_d2a_fb_3
            - workflow-job:1385.vb_58b_86ea_fff1
            - workflow-multibranch:773.vc4fe1378f1d5
            - workflow-scm-step:415.v434365564324
            - workflow-step-api:657.v03b_e8115821b_
            - workflow-support:865.v43e78cc44e0d
          persistence:
            enabled: true
            storageClass: "nfs-client"
            accessMode: "ReadWriteMany"
          containerEnv:
           - name: JENKINS_UC
             value: "https://updates.jenkins.io"
           - name: JENKINS_UC_EXPERIMENTAL
             value: "https://updates.jenkins.io/experimental"
           - name: JENKINS_INCREMENTALS_REPO_MIRROR
             value: "https://repo.jenkins-ci.org/incrementals"
           - name: JENKINS_PLUGIN_INFO
             value: "https://updates.jenkins.io/current/plugin-versions.json"
    register: jenkins_chart_output

  - name: Echo jenkins_chart_output
    debug:
      var: jenkins_chart_output

  - name: Wait until pod is ready
    shell:
      cmd: "kubectl wait --for=condition=ready pod --all -n jenkins --timeout=600s"

  - name: Get jenkins admin password
    ansible.builtin.shell:
      cmd: "kubectl exec --namespace jenkins -it svc/jenkins -c jenkins -- /bin/cat /run/secrets/additional/chart-admin-password && echo"
    register: jenkins_admin_pass
  - name: Get jenkins port
    ansible.builtin.shell:
      cmd: "kubectl get --namespace jenkins -o jsonpath=\"{.spec.ports[0].nodePort}\" services jenkins"
    register: jenkins_port
  - name: Get jenkins node
    ansible.builtin.shell:
      cmd: "kubectl describe po jenkins-0 -n jenkins | grep 'Node:'"
    register: jenkins_node

  - name: Echo jenkins_chart_output
    debug:
      msg:
        - "Jenkins node: {{ jenkins_node.stdout_lines }}"
        - "Jenkins port: {{ jenkins_port.stdout_lines }}"
        - "Jenkins admin password: {{ jenkins_admin_pass.stdout_lines }}"

