---
- name: Install Ingress Nginx in Kuber
  gather_facts: True
  hosts: kube_control_plane
  tasks:
  - name: Add Ingress Nginx chart repo
    kubernetes.core.helm_repository:
      name: ingress-nginx
      repo_url: "https://kubernetes.github.io/ingress-nginx"

  - name: Deploy latest Ingress Nginx chart
    kubernetes.core.helm:
      name: ingress-nginx
      chart_ref: ingress-nginx/ingress-nginx
      release_namespace: ingress-nginx
      create_namespace: true

  - name: Wait until Ingress Nginx is ready
    ansible.builtin.shell:
      cmd: "kubectl wait --for=condition=ready pod --all -n ingress-nginx --timeout=300s"